#!/usr/bin/env bash
# Install nginx web server
# Update package lists and install Nginx
apt-get update
apt-get install -y nginx

# Configure redirection
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.example.com/;\n\t}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
