#!/usr/bin/env bash
# Create custom 404 page
ERROR_COPY="Ceci n'est pas une page - 404"

apt-get -y update
apt-get -y install nginx

echo "$ERROR_COPY" /var/www/html/custom_404.html > /dev/null
sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx start