#!/usr/bin/env bash
# Create custom 404 page
ERROR_COPY="Ceci n'est pas une page - 404"

apt-get -y update
apt-get -y install nginx

echo "$ERROR_COPY" /var/www/html/custom_404.html > /dev/null
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.example.com/;\n\t}' /etc/nginx/sites-available/default
sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx restart