#!/usr/bin/env bash
# Configure nginx web server with custom response header

INDEX_COPY=
ERROR_COPY=

apt-get -y update
apt-get -y install nginx

echo "Holberton School for the win!" | tee /var/www/html/index.nginx-debian.html > /dev/null
echo "Ceci n'est pas une page - 404" | tee /var/www/html/custom_404.html > /dev/null

# config redirection
sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# config custom 404
sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# shellcheck disable=SC2154
# config custom response header
sed -i '/^\slocation.*/i \        add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# run server
service nginx start
