#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.

while IFS=: read -r username  password uid gid comment home shell; do
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password , more info about the user here: $comment"
done < /etc/passwd
