#!/usr/bin/env bash
#Write a Bash script that displays numbers from 1 to 20 and:

i=1

while ((i <= 20)); do
    case $i in
        4)
            echo "$i"
            echo "bad luck from China"
            ;;
        9)
            echo "$i"
            echo "bad luck from Japan"
            ;;
        17)
            echo "$i"
            echo "bad luck from Italy"
            ;;
        *)
            echo "$i"
            ;;
    esac
    i=$((i + 1))
done
