#!/usr/bin/env bash
# Bash script that displays the time for 12 h and 59 m:

h=0
m=1
while [ $h -le 12 ]; do
    echo "Hour: $h"
    while [ $m -le 59 ]; do
        echo "$m"
        ((m++))
        if [ "$m" -eq 60 ]; then
            m=0
            break
        fi
    done
    ((h++))
done
