#!/usr/bin/env bash
# a Bash script that configures an Ubuntu server with the below


cp /etc/hosts ~/hosts.new
filepath=~/hosts.new
if grep -q "localhost" "$filepath"; then
	sed -i '/localhost/ c\127.0.0.2 localhost' "$filepath"

else
	echo "127.0.0.2 localhost" >> ~/hosts.new
fi

if grep -q "facebook.com" "$filepath"; then
	sed -i '/facebook.com/ c\8.8.8.8 facebook.com' "$filepath"

else
	echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

cp -f ~/hosts.new /etc/hosts
