#!/usr/bin/env bash
# Get all active IPv4 addresses using ifconfig

ipv4_addresses=$(ifconfig | grep -oE 'inet (addr:)?([0-9]*\.){3}[0-9]*' | awk '{print $2}')

# Check if any IPv4 addresses were found
if [ -n "$ipv4_addresses" ]; then
    echo "$ipv4_addresses"
fi
