#!/usr/bin/env bash
#configures nginx to listen on port 8080 and run as user nginx
sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i '/listen       80;/a \    listen 8080;' /etc/nginx/sites-available/default
service nginx restart
