#!/usr/bin/env bash
#configures nginx to listen on port 8080 and run as user nginx
sudo sed -i 's/user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i '/listen\s\+80\s\+\(?:default_server\s\+\)\?;/a \    listen 8080;' /etc/nginx/sites-available/default
sudo service nginx restart
