#!/usr/bin/env bash
# a Bash script that uses ssh to connect
#to your server using the private key
#~/.ssh/school with the user ubuntu.
# Define variables
server_ip="100.24.242.165"
private_key="~/.ssh/school"
user="ubuntu"

# SSH connection using single-character flags
ssh -i "$private_key" "$user"@"$server_ip"
